CREATE DATABASE desafio_pensador;

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY, 
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS thoughts (
  id SERIAL PRIMARY KEY,
 	id_quote INTEGER REFERENCES users(id) NOT NULL,
	quote TEXT NOT NULL,
  quote_date TIMESTAMP DEFAULT NOW(),
  likes INTEGER
);